[build]
  command = "npm run build"
  publish = "build"

# proxy do Render (TWÓJ URL API)
[[redirects]]
  from = "/api/*"
  to = "https://investigation-in-10-rooms.onrender.com/:splat"
  status = 200
  force = true

# SPA fallback - NA KOŃCU
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
